import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./componentes/header";
import Footer from "./componentes/footer";

const inter = Inter({
  variable: "--inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Examen David Henrique UF4",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //agrege el fondo negro y la fuente 
  return (
    <html lang="en">
      <body className={`bg-black ${inter.variable} `}>
     
          <Header />
        <main>{children}</main>
          <Footer />
    
      </body>
    </html>
  );
}
